# Generated by Django 5.1.5 on 2025-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Nazev knihy"
                    ),
                ),
                ("pages", models.IntegerField(verbose_name="Pocet stranek")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="vytvoreno"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="update zaznamu"
                    ),
                ),
            ],
        ),
    ]
