# Generated by Django 5.1.5 on 2025-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="Popis knihy"),
        ),
    ]
