# Generated by Django 5.1.5 on 2025-02-18 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Pocet stranek",
            ),
        ),
    ]
