# Generated by Django 5.1.5 on 2025-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_bestseller",
            field=models.BooleanField(
                default=False, verbose_name="Je to bestseller?: "
            ),
        ),
    ]
